---
- include_tasks:                '../tasks/install_files.yml'
- include_tasks:                '../tasks/template_files.yml'
- include_tasks:                '../tasks/apt_update.yml'
  when:                         template_files_result.changed
